title = "Vasilios Syrakis"
description = "A simple blog made with Zola and Duckquill"
base_url = "https://vsyrakis.dev"
theme = "duckquill"

compile_sass = true
minify_html = true
build_search_index = true
generate_feeds = true
author = "Vasilios Syrakis"

taxonomies = [{ name = "tags", feed = true }]

[search]
index_format = "fuse_json"

[markdown]
smart_punctuation = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
theme = "tokyo-night"

[extra]
emoji_favicon = "🌘"
accent_color = "plum"
show_reading_time = true
show_share_button = true
default_theme = "dark"
scripts = ["presentation.js"]
styles = ["presentation.css", "presence.css"]

# Set this to the public HTTPS origin of the Phoenix app to enable presence.
# For example: "https://presence.example.com"
presence_server_url = "https://presence.vsyrakis.dev"

[extra.nav]
links = [
	{ name = "Blog",     url = "@/blog/_index.md" },
	{ name = "Links",    url = "@/links.md" },
	{ name = "PGP",      url = "@/pgp.md" },
	{ name = "CV",      url = "/cv.pdf" },
    #{ url = "tags", name = "Tags" }
]

[extra.footer]
show_copyright = true
show_powered_by = true
links = []
